# Generated by Django 6.0 on 2025-12-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='musician',
            table='musician',
        ),
    ]
