# Generated by Django 6.0 on 2025-12-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='first_cup',
            field=models.DateField(blank=True, null=True),
        ),
    ]
