# Generated by Django 6.0 on 2025-12-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group',
            new_name='pets',
        ),
    ]
