# Generated by Django 6.0 on 2025-12-11 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_rename_group_group_pets'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='pets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='pets.pet'),
        ),
    ]
