# Generated by Django 6.0 on 2025-12-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_pets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='pets',
        ),
    ]
