# Generated by Django 6.0 on 2025-12-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='patient',
            field=models.ManyToManyField(related_name='medics', through='hospital.Schedule', to='hospital.patient'),
        ),
    ]
